name: cursus_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  flutter_mobx: ^2.0.0
  mobx: ^2.0.7
  dio: ^4.0.0
  intl: ^0.17.0
  pedantic: ^1.11.0
  nil: ^1.1.1
  json_serializable: ^5.0.2
  infinite_scroll_pagination: ^3.0.1+1
  cupertino_icons: ^1.0.2
  flutter_credit_card: ^2.0.0
  freezed_annotation: ^0.14.1
  url_launcher: ^6.0.6
  get_storage: ^2.0.2
  get_it: ^7.1.3
  flutter_svg_provider: ^0.1.9
  auto_route: ^3.2.1
  analyzer: ^2.5.0
  mailto: ^2.0.0
  android_intent: ^2.0.0
  overlay_support: ^1.2.1
  uuid: ^3.0.4
  flutter_dotenv: ^5.0.0
  scroll_snap_list: ^0.8.1
  cached_network_image: ^3.0.0
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  flutter_svg: ^0.22.0
  flutter_launcher_icons: ^0.9.0
  bubble_tab_indicator: ^0.1.6
  buttons_tabbar: ^1.3.0
  easy_localization: ^3.0.0
  curved_navigation_bar: ^1.0.1
  smooth_page_indicator: ^0.3.0-nullsafety.0
  mask_text_input_formatter: ^2.0.0
  location: ^4.3.0
  #firebase_messaging: ^11.4.3
  firebase_auth: ^3.1.1
  google_sign_in: ^5.1.0
  device_info_plus: ^2.1.0
  google_maps_flutter: ^2.0.11
  flutter_google_places: ^0.3.0
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  flutter_local_notifications: ^9.0.2
  awesome_notifications: any
  local_auth: ^1.1.9
  image_picker: ^0.8.4+4
  webview_flutter: ^3.0.0
  basic_utils: ^3.9.0
  firebase_core: ^1.19.1
  firebase_messaging: ^11.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  freezed: ^0.14.1+3
  auto_route_generator: ^3.2.1
  import_sorter: ^4.5.0

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  build:watch: flutter pub run build_runner watch --delete-conflicting-outputs

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/ic_launcher.png"


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato/Lato-Italic.ttf
        - asset: assets/fonts/Lato/Lato-Light.ttf
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Thin.ttf
        - asset: assets/fonts/Lato/Lato-ThinItalic.ttf

    - family:  CursusIcons
      fonts:
        - asset: assets/fonts/CursusIcons.ttf

  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/images/
    - assets/translations/


